# Generated by Django 5.1.4 on 2025-01-08 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0002_review_stars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='movie',
        ),
        migrations.AddField(
            model_name='director',
            name='movie_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='reviews',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movie_app.review'),
        ),
    ]
