# Generated by Django 5.1.4 on 2025-01-08 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0003_remove_review_movie_director_movie_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='reviews',
        ),
        migrations.AddField(
            model_name='movie',
            name='reviews',
            field=models.ManyToManyField(null=True, to='movie_app.review'),
        ),
    ]
