# Generated by Django 5.1.4 on 2025-01-09 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0006_alter_review_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='director',
            name='movie_count',
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='director', to='movie_app.director'),
        ),
    ]
